all:
  hosts:
    # 192.168.183.205:
    #   ansible_host: 192.168.183.205
    #   ansible_user: keygen
    #   ansible_password: Q1w2e3r4
    #   ansible_python_interpreter: /usr/bin/python3
  children:
    zookeeper:
      hosts:
        # 192.168.183.205
    solr:
      hosts:
        # 192.168.183.205
    kafka:
      hosts:
        # 192.168.183.205
        

            




