all:
  vars:
    gcp_ssh_user: "keygen"
  hosts:
    solr-dev:
      gcp_terraform_machine_type: n1-standard-1
      gcp_terraform_image: ubuntu-1804-lts
      gcp_terraform_zone: us-central1-a
      gcp_terraform_label_assigned_products: zookeeper-solr
      ansible_python_interpreter: /usr/bin/python3
    kafka-dev:
      gcp_terraform_machine_type: n1-standard-1
      gcp_terraform_image: ubuntu-1804-lts
      gcp_terraform_zone: us-central1-a
      gcp_terraform_label_assigned_products: zookeeper-kafka
      ansible_python_interpreter: /usr/bin/python3
    sftp-dev:
      gcp_terraform_machine_type: n1-standard-1
      gcp_terraform_image: ubuntu-1804-lts
      gcp_terraform_zone: us-central1-a
      gcp_terraform_label_assigned_products: sftp
      ansible_python_interpreter: /usr/bin/python3
  children:
    java:
      children:
        zookeeper:
          hosts:
            solr-dev:
          vars:
            zookeeper_distribution_url: "http://mirror.linux-ia64.org/apache/zookeeper/zookeeper-3.6.1/apache-zookeeper-3.6.1-bin.tar.gz"
            zookeeper_distribution_dest: "/tmp/apache-zookeeper-3.6.1-bin.tar.gz"
            zookeeper_root: "/srv/zookeeper"
            zookeeper_service_user: "zk_service"
            zookeeper_service_user_password: "$6$mysalt$cmk99ocCqrrYSxgm5Ym4MXpPmDnoSZJVcZAWS.Z3MufYfIYIiEk0HUZGLY4ulVPfZMpHJvYjH/mFKjSbOPAh40"
            zookeeper_instances_count: 3
        solr:
          hosts:
            solr-dev:
          vars:
            solr_distribution_url: "http://mirror.linux-ia64.org/apache/lucene/solr/8.6.2/solr-8.6.2.tgz"
            solr_distribution_dest: "/tmp/solr-8.6.1.tgz"
            solr_root: "/srv/solr"
            solr_service_user: "solr_service"
            solr_service_user_password: "$6$mysalt$cmk99ocCqrrYSxgm5Ym4MXpPmDnoSZJVcZAWS.Z3MufYfIYIiEk0HUZGLY4ulVPfZMpHJvYjH/mFKjSbOPAh40"
            solr_instances_count: 3
            # currently not used, in solr settings Ansible wrote external ip address which gets from terraform
            solr_dns_name: solr.it-mastera.ru
        kafka:
          hosts:
            kafka-dev:
          vars:
            kafka_distribution_url: "https://apache-mirror.rbc.ru/pub/apache/kafka/2.6.0/kafka_2.13-2.6.0.tgz"
            kafka_distribution_dest: "/tmp/kafka_2.13-2.6.0.tgz"
            kafka_root: "/srv/kafka"
            kafka_service_user: "kafka_service"
            kafka_service_user_password: "$6$mysalt$cmk99ocCqrrYSxgm5Ym4MXpPmDnoSZJVcZAWS.Z3MufYfIYIiEk0HUZGLY4ulVPfZMpHJvYjH/mFKjSbOPAh40"
            kafka_instances_count: 3
            # currently not used, in kafka settings Ansible wrote external ip address which gets from terraform
            kafka_dns_name: kafka.it-mastera.ru
    sftp:
      hosts:
        sftp-dev:
      vars:
        sftp_home_partition: "/srv/sftp"
        sftp_allow_passwords: True
        sftp_enable_logging: True
        sftp_users:
        - name: user1
          password: "$1$salty$TzEgY7rlevpKGaF7Ey37k." # Q1w2e3r4
          shell: False
        - name: user2
          password: "$1$salty$TzEgY7rlevpKGaF7Ey37k." # Q1w2e3r4
          shell: False
        sftp_directories:
          - { name: public, mode: 755 }
        
