---
- name: "Create public storage bucket"
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
  - import_tasks: tasks/gcp-bucket-lb.yml
    tags: [ "terraform-glb" ]

- name: "Create GCE machines and populates Ansible inventory"
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
  - import_tasks: tasks/gcp-ce-vm.yml
    tags: [ "terraform-vm" ]

- name: "Install required software"
  hosts: java
  gather_facts: no
  become: yes
  tasks:
  - name: Wait for SSH to become open on the host
    wait_for_connection:
  - name: Install Java
    apt:
      name: default-jdk
      state: present
      update_cache: yes
  tags: [ "java" ]

- name: "Install Zookeeper"
  hosts: zookeeper
  gather_facts: yes
  become: yes
  roles:
    - { role: zookeeper }
  tags: [ "zookeeper" ]


- name: "Install SolrCloud"
  hosts: solr
  gather_facts: no
  become: yes
  roles:
    - { role: solrcloud }
  tags: [ "solrcloud" ]


- name: "Install Kafka and Confluent Schema"
  hosts: kafka
  gather_facts: no
  become: yes
  roles:
    - kafka
    - confluent-schema
  tags: [ "kafka" ]

- name: "Configure SFTP server"
  hosts: sftp
  become: yes
  roles:
    - sftp
  tags: [ "sftp" ]
