---
- name: "Zookeeper setup"
  hosts: all
  gather_facts: no
#  remote_user: keygen
  become: yes

  tasks:
  - name: Install Java
    apt:
      name: default-jdk
      state: present
      update_cache: yes

  - name: Download Zookeeper
    get_url:
      url: http://mirror.linux-ia64.org/apache/zookeeper/zookeeper-3.6.1/apache-zookeeper-3.6.1-bin.tar.gz
      dest: /srv/apache-zookeeper-3.6.1-bin.tar.gz

  - name: Create zookeeper-1 data
    file:
      path: /srv/zoo1/data
      state: directory

  - name: Create zookeeper-1 myid
    file:
      path: /srv/zoo1/data/myid
      state: touch

  - name: Add id
    lineinfile:
      path: /srv/zoo1/data/myid
      line: 1
      create: yes

  - name: Create zookeeper-2 data
    file:
      path: /srv/zoo2/data
      state: directory

  - name: Create zookeeper-2 myid
    file:
      path: /srv/zoo2/data/myid
      state: touch

  - name: Add id
    lineinfile:
      path: /srv/zoo2/data/myid
      line: 2
      create: yes

  - name: Create zookeeper-3 data
    file:
      path: /srv/zoo3/data
      state: directory

  - name: Create zookeeper-3 myid
    file:
      path: /srv/zoo3/data/myid
      state: touch

  - name: Add id
    lineinfile:
      path: /srv/zoo3/data/myid
      line: 3
      create: yes

  - name: Unpack Zookeeper 1
    unarchive:
      remote_src: yes
      src: /srv/apache-zookeeper-3.6.1-bin.tar.gz
      dest: /srv/zoo1
      extra_opts: [--strip-components=1]

  - name: Unpack Zookeeper 2
    unarchive:
      remote_src: yes
      src: /srv/apache-zookeeper-3.6.1-bin.tar.gz
      dest: /srv/zoo2
      extra_opts: [--strip-components=1]

  - name: Unpack Zookeeper 3
    unarchive:
      remote_src: yes
      src: /srv/apache-zookeeper-3.6.1-bin.tar.gz
      dest: /srv/zoo3
      extra_opts: [--strip-components=1]
  
  - name: Create zookeeper-3 conf
    file:
      path: /srv/zoo3/conf
      state: directory

  - name: Create zookeeper-2 conf
    file:
      path: /srv/zoo2/conf
      state: directory

  - name: Create zookeeper-1 conf
    file:
      path: /srv/zoo1/conf
      state: directory

  - name: Put zookeeper-1 config
    copy:
      src: zoo1.cfg
      dest: /srv/zoo1/conf/zoo.cfg

  - name: Put zookeeper-2 config
    copy:
      src: zoo2.cfg
      dest: /srv/zoo2/conf/zoo.cfg

  - name: Put zookeeper-3 config
    copy:
      src: zoo3.cfg
      dest: /srv/zoo3/conf/zoo.cfg