---
kafka_distribution_url: ""
kafka_distribution_dest: ""
kafka_root: ""
kafka_service_user: ""
# password: Hdosuwn763Hgpo
# command to generate: ansible all -i localhost, -m debug -a "msg={{ 'Hdosuwn763Hgpo' | password_hash('sha512', 'mysalt') }}"
kafka_service_user_password: ""

kafka_instances_count: 3
kafka_dns_name: 192.168.183.205