---
- name: "Zookeeper setup"
  hosts: all
  gather_facts: no
#  remote_user: keygen
  become: yes

  tasks:
  - name: Download Kafka
    get_url:
      url: https://apache-mirror.rbc.ru/pub/apache/kafka/2.6.0/kafka_2.13-2.6.0.tgz
      dest: /srv/kafka_2.13-2.6.0.tgz

  - name: Download Confluent
    get_url:
      url: https://packages.confluent.io/archive/5.5/confluent-5.5.1-2.12.tar.gz
      dest: /srv/confluent-5.5.1-2.12.tar.gz

  - name: Create kafka dir
    file:
      path: /srv/kafka
      state: directory

  - name: Create confluent dir
    file:
      path: /srv/confluent
      state: directory

  - name: Unpack Confluent
    unarchive:
      remote_src: yes
      src: /srv/confluent-5.5.1-2.12.tar.gz
      dest: /srv/confluent
      extra_opts: [--strip-components=1]

  - name: Unpack Kafka
    unarchive:
      remote_src: yes
      src: /srv/kafka_2.13-2.6.0.tgz
      dest: /srv/kafka
      extra_opts: [--strip-components=1]

  - name: Put config
    copy:
      src: schema-registry.properties
      dest: /srv/confluent/etc/schema-registry/schema-registry.properties

  - name: Put config
    copy:
      src: server1.properties
      dest: /srv/kafka/config/server1.properties

  - name: Put config
    copy:
      src: server2.properties
      dest: /srv/kafka/config/server2.properties

  - name: Put config
    copy:
      src: server3.properties
      dest: /srv/kafka/config/server3.properties

  - name: Delete server.properties
    file:
      path: /srv/kafka/config/server.properties
      state: absent
